name: Run tests on CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: 3.6
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        MONGODB_URI: mongodb://localhost:27017/test-sensors
